version: "3"

services:
  frontend:
    build: ./gorju/frontend
    tty: true
    stdin_open: true
    networks:
      - frontend
    depends_on:
      - user_app
      - vehicleapp
      - booking_app
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - frontend
      - vehicleapp
      - user_app
      - booking_app
  booking_app:
    build: ./gorju/booking-management
    environment:
    - SERVICE_PORT=${SERVICE_PORT}
    - DATABASE_URL=mongodb://mongodb:27017/gorju-cars
    networks: 
      - backend
    depends_on:
      - mongodb
  user_app:
    build: ./gorju/user-management
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
      - DATABASE_URL=mongodb://mongodb:27017/gorju-cars
    networks:
      - backend
    depends_on:
      - mongodb
  vehicleapp:
    build: ./gorju/vehicle-management
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
    networks:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
