# maven github workflow running maven clean test
name: maven

on:
  push:
    branches:
      - julianne
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean test --file CPS2002-Gorju_Car_Rental/pom.xml

# The above workflow will checkout the code from the repository and run the maven build. The workflow will be triggered on every push to the repository.



